title: Prediksi Hk Mbah Semar
author:
  name: HK Mbah Semar
  email: Megafitria297@gmail.com
description: Prediksi Hk Mbah Semar Hari Ini, Hk Mbah Semar, Prediksi Hk
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: dark
